package cn.guddqs.peakshop.entity;

import java.util.Date;

public class AddressInfo {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column address_info.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column address_info.user_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer userId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column address_info.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column address_info.phone
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column address_info.post_no
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String postNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column address_info.address
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column address_info.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Date startTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column address_info.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Date endTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column address_info.is_default
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Boolean isDefault;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column address_info.id
	 * @return  the value of address_info.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column address_info.id
	 * @param id  the value for address_info.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column address_info.user_id
	 * @return  the value of address_info.user_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column address_info.user_id
	 * @param userId  the value for address_info.user_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column address_info.name
	 * @return  the value of address_info.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column address_info.name
	 * @param name  the value for address_info.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column address_info.phone
	 * @return  the value of address_info.phone
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column address_info.phone
	 * @param phone  the value for address_info.phone
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column address_info.post_no
	 * @return  the value of address_info.post_no
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getPostNo() {
		return postNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column address_info.post_no
	 * @param postNo  the value for address_info.post_no
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setPostNo(String postNo) {
		this.postNo = postNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column address_info.address
	 * @return  the value of address_info.address
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column address_info.address
	 * @param address  the value for address_info.address
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column address_info.start_time
	 * @return  the value of address_info.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column address_info.start_time
	 * @param startTime  the value for address_info.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column address_info.end_time
	 * @return  the value of address_info.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column address_info.end_time
	 * @param endTime  the value for address_info.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column address_info.is_default
	 * @return  the value of address_info.is_default
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Boolean getIsDefault() {
		return isDefault;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column address_info.is_default
	 * @param isDefault  the value for address_info.is_default
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}
}