package cn.guddqs.peakshop.entity;

import java.util.Date;

public class Cart {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cart.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cart.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer productId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cart.color_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer colorId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cart.size_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer sizeId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cart.number
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer number;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cart.mode
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer mode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cart.checked
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Boolean checked;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cart.add_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Date addTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cart.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Date editTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column cart.user_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer userId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cart.id
	 * @return  the value of cart.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cart.id
	 * @param id  the value for cart.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cart.product_id
	 * @return  the value of cart.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cart.product_id
	 * @param productId  the value for cart.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cart.color_id
	 * @return  the value of cart.color_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getColorId() {
		return colorId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cart.color_id
	 * @param colorId  the value for cart.color_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setColorId(Integer colorId) {
		this.colorId = colorId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cart.size_id
	 * @return  the value of cart.size_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getSizeId() {
		return sizeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cart.size_id
	 * @param sizeId  the value for cart.size_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setSizeId(Integer sizeId) {
		this.sizeId = sizeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cart.number
	 * @return  the value of cart.number
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getNumber() {
		return number;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cart.number
	 * @param number  the value for cart.number
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setNumber(Integer number) {
		this.number = number;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cart.mode
	 * @return  the value of cart.mode
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getMode() {
		return mode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cart.mode
	 * @param mode  the value for cart.mode
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setMode(Integer mode) {
		this.mode = mode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cart.checked
	 * @return  the value of cart.checked
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Boolean getChecked() {
		return checked;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cart.checked
	 * @param checked  the value for cart.checked
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cart.add_time
	 * @return  the value of cart.add_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cart.add_time
	 * @param addTime  the value for cart.add_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cart.edit_time
	 * @return  the value of cart.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Date getEditTime() {
		return editTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cart.edit_time
	 * @param editTime  the value for cart.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column cart.user_id
	 * @return  the value of cart.user_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column cart.user_id
	 * @param userId  the value for cart.user_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}