package cn.guddqs.peakshop.entity;

public class Color {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column color.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column color.name
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private String name;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column color.id
	 * @return  the value of color.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column color.id
	 * @param id  the value for color.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column color.name
	 * @return  the value of color.name
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column color.name
	 * @param name  the value for color.name
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}
}