package cn.guddqs.peakshop.entity;

public class MerchantInfo {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column merchant_info.id
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column merchant_info.address
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	private String address;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column merchant_info.phone
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column merchant_info.email
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column merchant_info.weixin
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	private String weixin;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column merchant_info.qq
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	private String qq;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column merchant_info.name
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column merchant_info.password
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	private String password;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column merchant_info.id
	 * @return  the value of merchant_info.id
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column merchant_info.id
	 * @param id  the value for merchant_info.id
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column merchant_info.address
	 * @return  the value of merchant_info.address
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column merchant_info.address
	 * @param address  the value for merchant_info.address
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column merchant_info.phone
	 * @return  the value of merchant_info.phone
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column merchant_info.phone
	 * @param phone  the value for merchant_info.phone
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column merchant_info.email
	 * @return  the value of merchant_info.email
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column merchant_info.email
	 * @param email  the value for merchant_info.email
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column merchant_info.weixin
	 * @return  the value of merchant_info.weixin
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public String getWeixin() {
		return weixin;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column merchant_info.weixin
	 * @param weixin  the value for merchant_info.weixin
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public void setWeixin(String weixin) {
		this.weixin = weixin;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column merchant_info.qq
	 * @return  the value of merchant_info.qq
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column merchant_info.qq
	 * @param qq  the value for merchant_info.qq
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column merchant_info.name
	 * @return  the value of merchant_info.name
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column merchant_info.name
	 * @param name  the value for merchant_info.name
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column merchant_info.password
	 * @return  the value of merchant_info.password
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column merchant_info.password
	 * @param password  the value for merchant_info.password
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}