package cn.guddqs.peakshop.entity;

public class ProductSize {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_size.id
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_size.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	private Integer productId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_size.size_id
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	private Integer sizeId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_size.id
	 * @return  the value of product_size.id
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_size.id
	 * @param id  the value for product_size.id
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_size.product_id
	 * @return  the value of product_size.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_size.product_id
	 * @param productId  the value for product_size.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_size.size_id
	 * @return  the value of product_size.size_id
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public Integer getSizeId() {
		return sizeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_size.size_id
	 * @param sizeId  the value for product_size.size_id
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public void setSizeId(Integer sizeId) {
		this.sizeId = sizeId;
	}
}