package cn.guddqs.peakshop.entity;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.picture
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String picture;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Double price;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.prevprice
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Double prevprice;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.type_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer typeId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.is_show
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer isShow;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.is_hot
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer isHot;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.is_discount
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer isDiscount;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.is_groupbuy
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer isGroupbuy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.groupbuy_price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Double groupbuyPrice;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.groupbuy_num
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer groupbuyNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.show_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Date showTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Date editTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.is_new
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer isNew;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.product_no
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String productNo;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.name
	 * @return  the value of product.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.name
	 * @param name  the value for product.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.picture
	 * @return  the value of product.picture
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.picture
	 * @param picture  the value for product.picture
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.price
	 * @return  the value of product.price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.price
	 * @param price  the value for product.price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.prevprice
	 * @return  the value of product.prevprice
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Double getPrevprice() {
		return prevprice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.prevprice
	 * @param prevprice  the value for product.prevprice
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setPrevprice(Double prevprice) {
		this.prevprice = prevprice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.type_id
	 * @return  the value of product.type_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.type_id
	 * @param typeId  the value for product.type_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.is_show
	 * @return  the value of product.is_show
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getIsShow() {
		return isShow;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.is_show
	 * @param isShow  the value for product.is_show
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.is_hot
	 * @return  the value of product.is_hot
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getIsHot() {
		return isHot;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.is_hot
	 * @param isHot  the value for product.is_hot
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setIsHot(Integer isHot) {
		this.isHot = isHot;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.is_discount
	 * @return  the value of product.is_discount
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getIsDiscount() {
		return isDiscount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.is_discount
	 * @param isDiscount  the value for product.is_discount
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setIsDiscount(Integer isDiscount) {
		this.isDiscount = isDiscount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.is_groupbuy
	 * @return  the value of product.is_groupbuy
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getIsGroupbuy() {
		return isGroupbuy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.is_groupbuy
	 * @param isGroupbuy  the value for product.is_groupbuy
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setIsGroupbuy(Integer isGroupbuy) {
		this.isGroupbuy = isGroupbuy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.groupbuy_price
	 * @return  the value of product.groupbuy_price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Double getGroupbuyPrice() {
		return groupbuyPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.groupbuy_price
	 * @param groupbuyPrice  the value for product.groupbuy_price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setGroupbuyPrice(Double groupbuyPrice) {
		this.groupbuyPrice = groupbuyPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.groupbuy_num
	 * @return  the value of product.groupbuy_num
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getGroupbuyNum() {
		return groupbuyNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.groupbuy_num
	 * @param groupbuyNum  the value for product.groupbuy_num
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setGroupbuyNum(Integer groupbuyNum) {
		this.groupbuyNum = groupbuyNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.show_time
	 * @return  the value of product.show_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Date getShowTime() {
		return showTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.show_time
	 * @param showTime  the value for product.show_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setShowTime(Date showTime) {
		this.showTime = showTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.edit_time
	 * @return  the value of product.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Date getEditTime() {
		return editTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.edit_time
	 * @param editTime  the value for product.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.is_new
	 * @return  the value of product.is_new
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getIsNew() {
		return isNew;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.is_new
	 * @param isNew  the value for product.is_new
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setIsNew(Integer isNew) {
		this.isNew = isNew;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.product_no
	 * @return  the value of product.product_no
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getProductNo() {
		return productNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.product_no
	 * @param productNo  the value for product.product_no
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}
}