package cn.guddqs.peakshop.entity;

public class ProductColor {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_color.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_color.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer productId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_color.color_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer colorId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_color.id
	 * @return  the value of product_color.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_color.id
	 * @param id  the value for product_color.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_color.product_id
	 * @return  the value of product_color.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_color.product_id
	 * @param productId  the value for product_color.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_color.color_id
	 * @return  the value of product_color.color_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getColorId() {
		return colorId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_color.color_id
	 * @param colorId  the value for product_color.color_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setColorId(Integer colorId) {
		this.colorId = colorId;
	}
}