package cn.guddqs.peakshop.entity;

import java.util.Date;

public class ProductDetail {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_detail.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_detail.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer productId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_detail.picture
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private String picture;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_detail.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Date startTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product_detail.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Date editTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_detail.id
	 * @return  the value of product_detail.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_detail.id
	 * @param id  the value for product_detail.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_detail.product_id
	 * @return  the value of product_detail.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_detail.product_id
	 * @param productId  the value for product_detail.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_detail.picture
	 * @return  the value of product_detail.picture
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_detail.picture
	 * @param picture  the value for product_detail.picture
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_detail.start_time
	 * @return  the value of product_detail.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_detail.start_time
	 * @param startTime  the value for product_detail.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product_detail.edit_time
	 * @return  the value of product_detail.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Date getEditTime() {
		return editTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product_detail.edit_time
	 * @param editTime  the value for product_detail.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}
}