package cn.guddqs.peakshop.entity;

import java.util.Date;

public class Store {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column store.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column store.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer productId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column store.color_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer colorId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column store.size_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer sizeId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column store.store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer store;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column store.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Date startTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column store.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Date editTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column store.id
	 * @return  the value of store.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column store.id
	 * @param id  the value for store.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column store.product_id
	 * @return  the value of store.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column store.product_id
	 * @param productId  the value for store.product_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column store.color_id
	 * @return  the value of store.color_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getColorId() {
		return colorId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column store.color_id
	 * @param colorId  the value for store.color_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setColorId(Integer colorId) {
		this.colorId = colorId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column store.size_id
	 * @return  the value of store.size_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getSizeId() {
		return sizeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column store.size_id
	 * @param sizeId  the value for store.size_id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setSizeId(Integer sizeId) {
		this.sizeId = sizeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column store.store
	 * @return  the value of store.store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getStore() {
		return store;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column store.store
	 * @param store  the value for store.store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setStore(Integer store) {
		this.store = store;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column store.start_time
	 * @return  the value of store.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column store.start_time
	 * @param startTime  the value for store.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column store.edit_time
	 * @return  the value of store.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Date getEditTime() {
		return editTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column store.edit_time
	 * @param editTime  the value for store.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}
}