package cn.guddqs.peakshop.entity;

import java.util.Date;

public class TradeOrder {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.user_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer userId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.status
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer status;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.product_name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String productName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String addressInfo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.wuliu_no
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String wuliuNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.remark
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String remark;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.order_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String orderId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.total_price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Double totalPrice;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.number
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer number;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.color
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String color;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.size
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String size;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.phone
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Double price;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Date startTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Date endTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.picture
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String picture;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column trade_order.cart_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer cartId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.id
	 * @return  the value of trade_order.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.id
	 * @param id  the value for trade_order.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.user_id
	 * @return  the value of trade_order.user_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.user_id
	 * @param userId  the value for trade_order.user_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.status
	 * @return  the value of trade_order.status
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.status
	 * @param status  the value for trade_order.status
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.product_name
	 * @return  the value of trade_order.product_name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.product_name
	 * @param productName  the value for trade_order.product_name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.address_info
	 * @return  the value of trade_order.address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getAddressInfo() {
		return addressInfo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.address_info
	 * @param addressInfo  the value for trade_order.address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setAddressInfo(String addressInfo) {
		this.addressInfo = addressInfo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.wuliu_no
	 * @return  the value of trade_order.wuliu_no
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getWuliuNo() {
		return wuliuNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.wuliu_no
	 * @param wuliuNo  the value for trade_order.wuliu_no
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setWuliuNo(String wuliuNo) {
		this.wuliuNo = wuliuNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.remark
	 * @return  the value of trade_order.remark
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.remark
	 * @param remark  the value for trade_order.remark
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.order_id
	 * @return  the value of trade_order.order_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.order_id
	 * @param orderId  the value for trade_order.order_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.total_price
	 * @return  the value of trade_order.total_price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Double getTotalPrice() {
		return totalPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.total_price
	 * @param totalPrice  the value for trade_order.total_price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.number
	 * @return  the value of trade_order.number
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getNumber() {
		return number;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.number
	 * @param number  the value for trade_order.number
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setNumber(Integer number) {
		this.number = number;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.color
	 * @return  the value of trade_order.color
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getColor() {
		return color;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.color
	 * @param color  the value for trade_order.color
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setColor(String color) {
		this.color = color;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.size
	 * @return  the value of trade_order.size
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getSize() {
		return size;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.size
	 * @param size  the value for trade_order.size
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setSize(String size) {
		this.size = size;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.phone
	 * @return  the value of trade_order.phone
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.phone
	 * @param phone  the value for trade_order.phone
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.name
	 * @return  the value of trade_order.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.name
	 * @param name  the value for trade_order.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.price
	 * @return  the value of trade_order.price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.price
	 * @param price  the value for trade_order.price
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.start_time
	 * @return  the value of trade_order.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.start_time
	 * @param startTime  the value for trade_order.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.end_time
	 * @return  the value of trade_order.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.end_time
	 * @param endTime  the value for trade_order.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.picture
	 * @return  the value of trade_order.picture
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.picture
	 * @param picture  the value for trade_order.picture
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column trade_order.cart_id
	 * @return  the value of trade_order.cart_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getCartId() {
		return cartId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column trade_order.cart_id
	 * @param cartId  the value for trade_order.cart_id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}
}