package cn.guddqs.peakshop.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Iterator;

public class TradeOrderExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public TradeOrderExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	protected TradeOrderExample(TradeOrderExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return this;
		}

		public Criteria andUserIdIn(List values) {
			addCriterion("user_id in", values, "userId");
			return this;
		}

		public Criteria andUserIdNotIn(List values) {
			addCriterion("user_id not in", values, "userId");
			return this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("status in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("status not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("product_name is null");
			return this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("product_name is not null");
			return this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("product_name =", value, "productName");
			return this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("product_name <>", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("product_name >", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("product_name >=", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("product_name <", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("product_name <=", value, "productName");
			return this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("product_name like", value, "productName");
			return this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("product_name not like", value, "productName");
			return this;
		}

		public Criteria andProductNameIn(List values) {
			addCriterion("product_name in", values, "productName");
			return this;
		}

		public Criteria andProductNameNotIn(List values) {
			addCriterion("product_name not in", values, "productName");
			return this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("product_name between", value1, value2, "productName");
			return this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("product_name not between", value1, value2,
					"productName");
			return this;
		}

		public Criteria andAddressInfoIsNull() {
			addCriterion("address_info is null");
			return this;
		}

		public Criteria andAddressInfoIsNotNull() {
			addCriterion("address_info is not null");
			return this;
		}

		public Criteria andAddressInfoEqualTo(String value) {
			addCriterion("address_info =", value, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoNotEqualTo(String value) {
			addCriterion("address_info <>", value, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoGreaterThan(String value) {
			addCriterion("address_info >", value, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoGreaterThanOrEqualTo(String value) {
			addCriterion("address_info >=", value, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoLessThan(String value) {
			addCriterion("address_info <", value, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoLessThanOrEqualTo(String value) {
			addCriterion("address_info <=", value, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoLike(String value) {
			addCriterion("address_info like", value, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoNotLike(String value) {
			addCriterion("address_info not like", value, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoIn(List values) {
			addCriterion("address_info in", values, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoNotIn(List values) {
			addCriterion("address_info not in", values, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoBetween(String value1, String value2) {
			addCriterion("address_info between", value1, value2, "addressInfo");
			return this;
		}

		public Criteria andAddressInfoNotBetween(String value1, String value2) {
			addCriterion("address_info not between", value1, value2,
					"addressInfo");
			return this;
		}

		public Criteria andWuliuNoIsNull() {
			addCriterion("wuliu_no is null");
			return this;
		}

		public Criteria andWuliuNoIsNotNull() {
			addCriterion("wuliu_no is not null");
			return this;
		}

		public Criteria andWuliuNoEqualTo(String value) {
			addCriterion("wuliu_no =", value, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoNotEqualTo(String value) {
			addCriterion("wuliu_no <>", value, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoGreaterThan(String value) {
			addCriterion("wuliu_no >", value, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoGreaterThanOrEqualTo(String value) {
			addCriterion("wuliu_no >=", value, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoLessThan(String value) {
			addCriterion("wuliu_no <", value, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoLessThanOrEqualTo(String value) {
			addCriterion("wuliu_no <=", value, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoLike(String value) {
			addCriterion("wuliu_no like", value, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoNotLike(String value) {
			addCriterion("wuliu_no not like", value, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoIn(List values) {
			addCriterion("wuliu_no in", values, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoNotIn(List values) {
			addCriterion("wuliu_no not in", values, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoBetween(String value1, String value2) {
			addCriterion("wuliu_no between", value1, value2, "wuliuNo");
			return this;
		}

		public Criteria andWuliuNoNotBetween(String value1, String value2) {
			addCriterion("wuliu_no not between", value1, value2, "wuliuNo");
			return this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return this;
		}

		public Criteria andRemarkIn(List values) {
			addCriterion("remark in", values, "remark");
			return this;
		}

		public Criteria andRemarkNotIn(List values) {
			addCriterion("remark not in", values, "remark");
			return this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return this;
		}

		public Criteria andOrderIdEqualTo(String value) {
			addCriterion("order_id =", value, "orderId");
			return this;
		}

		public Criteria andOrderIdNotEqualTo(String value) {
			addCriterion("order_id <>", value, "orderId");
			return this;
		}

		public Criteria andOrderIdGreaterThan(String value) {
			addCriterion("order_id >", value, "orderId");
			return this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_id >=", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLessThan(String value) {
			addCriterion("order_id <", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(String value) {
			addCriterion("order_id <=", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLike(String value) {
			addCriterion("order_id like", value, "orderId");
			return this;
		}

		public Criteria andOrderIdNotLike(String value) {
			addCriterion("order_id not like", value, "orderId");
			return this;
		}

		public Criteria andOrderIdIn(List values) {
			addCriterion("order_id in", values, "orderId");
			return this;
		}

		public Criteria andOrderIdNotIn(List values) {
			addCriterion("order_id not in", values, "orderId");
			return this;
		}

		public Criteria andOrderIdBetween(String value1, String value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return this;
		}

		public Criteria andOrderIdNotBetween(String value1, String value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return this;
		}

		public Criteria andTotalPriceIsNull() {
			addCriterion("total_price is null");
			return this;
		}

		public Criteria andTotalPriceIsNotNull() {
			addCriterion("total_price is not null");
			return this;
		}

		public Criteria andTotalPriceEqualTo(Double value) {
			addCriterion("total_price =", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceNotEqualTo(Double value) {
			addCriterion("total_price <>", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceGreaterThan(Double value) {
			addCriterion("total_price >", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("total_price >=", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceLessThan(Double value) {
			addCriterion("total_price <", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceLessThanOrEqualTo(Double value) {
			addCriterion("total_price <=", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceIn(List values) {
			addCriterion("total_price in", values, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceNotIn(List values) {
			addCriterion("total_price not in", values, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceBetween(Double value1, Double value2) {
			addCriterion("total_price between", value1, value2, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceNotBetween(Double value1, Double value2) {
			addCriterion("total_price not between", value1, value2,
					"totalPrice");
			return this;
		}

		public Criteria andNumberIsNull() {
			addCriterion("number is null");
			return this;
		}

		public Criteria andNumberIsNotNull() {
			addCriterion("number is not null");
			return this;
		}

		public Criteria andNumberEqualTo(Integer value) {
			addCriterion("number =", value, "number");
			return this;
		}

		public Criteria andNumberNotEqualTo(Integer value) {
			addCriterion("number <>", value, "number");
			return this;
		}

		public Criteria andNumberGreaterThan(Integer value) {
			addCriterion("number >", value, "number");
			return this;
		}

		public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("number >=", value, "number");
			return this;
		}

		public Criteria andNumberLessThan(Integer value) {
			addCriterion("number <", value, "number");
			return this;
		}

		public Criteria andNumberLessThanOrEqualTo(Integer value) {
			addCriterion("number <=", value, "number");
			return this;
		}

		public Criteria andNumberIn(List values) {
			addCriterion("number in", values, "number");
			return this;
		}

		public Criteria andNumberNotIn(List values) {
			addCriterion("number not in", values, "number");
			return this;
		}

		public Criteria andNumberBetween(Integer value1, Integer value2) {
			addCriterion("number between", value1, value2, "number");
			return this;
		}

		public Criteria andNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("number not between", value1, value2, "number");
			return this;
		}

		public Criteria andColorIsNull() {
			addCriterion("color is null");
			return this;
		}

		public Criteria andColorIsNotNull() {
			addCriterion("color is not null");
			return this;
		}

		public Criteria andColorEqualTo(String value) {
			addCriterion("color =", value, "color");
			return this;
		}

		public Criteria andColorNotEqualTo(String value) {
			addCriterion("color <>", value, "color");
			return this;
		}

		public Criteria andColorGreaterThan(String value) {
			addCriterion("color >", value, "color");
			return this;
		}

		public Criteria andColorGreaterThanOrEqualTo(String value) {
			addCriterion("color >=", value, "color");
			return this;
		}

		public Criteria andColorLessThan(String value) {
			addCriterion("color <", value, "color");
			return this;
		}

		public Criteria andColorLessThanOrEqualTo(String value) {
			addCriterion("color <=", value, "color");
			return this;
		}

		public Criteria andColorLike(String value) {
			addCriterion("color like", value, "color");
			return this;
		}

		public Criteria andColorNotLike(String value) {
			addCriterion("color not like", value, "color");
			return this;
		}

		public Criteria andColorIn(List values) {
			addCriterion("color in", values, "color");
			return this;
		}

		public Criteria andColorNotIn(List values) {
			addCriterion("color not in", values, "color");
			return this;
		}

		public Criteria andColorBetween(String value1, String value2) {
			addCriterion("color between", value1, value2, "color");
			return this;
		}

		public Criteria andColorNotBetween(String value1, String value2) {
			addCriterion("color not between", value1, value2, "color");
			return this;
		}

		public Criteria andSizeIsNull() {
			addCriterion("size is null");
			return this;
		}

		public Criteria andSizeIsNotNull() {
			addCriterion("size is not null");
			return this;
		}

		public Criteria andSizeEqualTo(String value) {
			addCriterion("size =", value, "size");
			return this;
		}

		public Criteria andSizeNotEqualTo(String value) {
			addCriterion("size <>", value, "size");
			return this;
		}

		public Criteria andSizeGreaterThan(String value) {
			addCriterion("size >", value, "size");
			return this;
		}

		public Criteria andSizeGreaterThanOrEqualTo(String value) {
			addCriterion("size >=", value, "size");
			return this;
		}

		public Criteria andSizeLessThan(String value) {
			addCriterion("size <", value, "size");
			return this;
		}

		public Criteria andSizeLessThanOrEqualTo(String value) {
			addCriterion("size <=", value, "size");
			return this;
		}

		public Criteria andSizeLike(String value) {
			addCriterion("size like", value, "size");
			return this;
		}

		public Criteria andSizeNotLike(String value) {
			addCriterion("size not like", value, "size");
			return this;
		}

		public Criteria andSizeIn(List values) {
			addCriterion("size in", values, "size");
			return this;
		}

		public Criteria andSizeNotIn(List values) {
			addCriterion("size not in", values, "size");
			return this;
		}

		public Criteria andSizeBetween(String value1, String value2) {
			addCriterion("size between", value1, value2, "size");
			return this;
		}

		public Criteria andSizeNotBetween(String value1, String value2) {
			addCriterion("size not between", value1, value2, "size");
			return this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return this;
		}

		public Criteria andPhoneIn(List values) {
			addCriterion("phone in", values, "phone");
			return this;
		}

		public Criteria andPhoneNotIn(List values) {
			addCriterion("phone not in", values, "phone");
			return this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return this;
		}

		public Criteria andNameIn(List values) {
			addCriterion("name in", values, "name");
			return this;
		}

		public Criteria andNameNotIn(List values) {
			addCriterion("name not in", values, "name");
			return this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return this;
		}

		public Criteria andPriceIn(List values) {
			addCriterion("price in", values, "price");
			return this;
		}

		public Criteria andPriceNotIn(List values) {
			addCriterion("price not in", values, "price");
			return this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("start_time is null");
			return this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("start_time is not null");
			return this;
		}

		public Criteria andStartTimeEqualTo(Date value) {
			addCriterion("start_time =", value, "startTime");
			return this;
		}

		public Criteria andStartTimeNotEqualTo(Date value) {
			addCriterion("start_time <>", value, "startTime");
			return this;
		}

		public Criteria andStartTimeGreaterThan(Date value) {
			addCriterion("start_time >", value, "startTime");
			return this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("start_time >=", value, "startTime");
			return this;
		}

		public Criteria andStartTimeLessThan(Date value) {
			addCriterion("start_time <", value, "startTime");
			return this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Date value) {
			addCriterion("start_time <=", value, "startTime");
			return this;
		}

		public Criteria andStartTimeIn(List values) {
			addCriterion("start_time in", values, "startTime");
			return this;
		}

		public Criteria andStartTimeNotIn(List values) {
			addCriterion("start_time not in", values, "startTime");
			return this;
		}

		public Criteria andStartTimeBetween(Date value1, Date value2) {
			addCriterion("start_time between", value1, value2, "startTime");
			return this;
		}

		public Criteria andStartTimeNotBetween(Date value1, Date value2) {
			addCriterion("start_time not between", value1, value2, "startTime");
			return this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterion("end_time =", value, "endTime");
			return this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterion("end_time <>", value, "endTime");
			return this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterion("end_time >", value, "endTime");
			return this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("end_time >=", value, "endTime");
			return this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterion("end_time <", value, "endTime");
			return this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterion("end_time <=", value, "endTime");
			return this;
		}

		public Criteria andEndTimeIn(List values) {
			addCriterion("end_time in", values, "endTime");
			return this;
		}

		public Criteria andEndTimeNotIn(List values) {
			addCriterion("end_time not in", values, "endTime");
			return this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterion("end_time between", value1, value2, "endTime");
			return this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterion("end_time not between", value1, value2, "endTime");
			return this;
		}

		public Criteria andPictureIsNull() {
			addCriterion("picture is null");
			return this;
		}

		public Criteria andPictureIsNotNull() {
			addCriterion("picture is not null");
			return this;
		}

		public Criteria andPictureEqualTo(String value) {
			addCriterion("picture =", value, "picture");
			return this;
		}

		public Criteria andPictureNotEqualTo(String value) {
			addCriterion("picture <>", value, "picture");
			return this;
		}

		public Criteria andPictureGreaterThan(String value) {
			addCriterion("picture >", value, "picture");
			return this;
		}

		public Criteria andPictureGreaterThanOrEqualTo(String value) {
			addCriterion("picture >=", value, "picture");
			return this;
		}

		public Criteria andPictureLessThan(String value) {
			addCriterion("picture <", value, "picture");
			return this;
		}

		public Criteria andPictureLessThanOrEqualTo(String value) {
			addCriterion("picture <=", value, "picture");
			return this;
		}

		public Criteria andPictureLike(String value) {
			addCriterion("picture like", value, "picture");
			return this;
		}

		public Criteria andPictureNotLike(String value) {
			addCriterion("picture not like", value, "picture");
			return this;
		}

		public Criteria andPictureIn(List values) {
			addCriterion("picture in", values, "picture");
			return this;
		}

		public Criteria andPictureNotIn(List values) {
			addCriterion("picture not in", values, "picture");
			return this;
		}

		public Criteria andPictureBetween(String value1, String value2) {
			addCriterion("picture between", value1, value2, "picture");
			return this;
		}

		public Criteria andPictureNotBetween(String value1, String value2) {
			addCriterion("picture not between", value1, value2, "picture");
			return this;
		}

		public Criteria andCartIdIsNull() {
			addCriterion("cart_id is null");
			return this;
		}

		public Criteria andCartIdIsNotNull() {
			addCriterion("cart_id is not null");
			return this;
		}

		public Criteria andCartIdEqualTo(Integer value) {
			addCriterion("cart_id =", value, "cartId");
			return this;
		}

		public Criteria andCartIdNotEqualTo(Integer value) {
			addCriterion("cart_id <>", value, "cartId");
			return this;
		}

		public Criteria andCartIdGreaterThan(Integer value) {
			addCriterion("cart_id >", value, "cartId");
			return this;
		}

		public Criteria andCartIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("cart_id >=", value, "cartId");
			return this;
		}

		public Criteria andCartIdLessThan(Integer value) {
			addCriterion("cart_id <", value, "cartId");
			return this;
		}

		public Criteria andCartIdLessThanOrEqualTo(Integer value) {
			addCriterion("cart_id <=", value, "cartId");
			return this;
		}

		public Criteria andCartIdIn(List values) {
			addCriterion("cart_id in", values, "cartId");
			return this;
		}

		public Criteria andCartIdNotIn(List values) {
			addCriterion("cart_id not in", values, "cartId");
			return this;
		}

		public Criteria andCartIdBetween(Integer value1, Integer value2) {
			addCriterion("cart_id between", value1, value2, "cartId");
			return this;
		}

		public Criteria andCartIdNotBetween(Integer value1, Integer value2) {
			addCriterion("cart_id not between", value1, value2, "cartId");
			return this;
		}
	}
}