package cn.guddqs.peakshop.entity;

import java.util.Date;

public class Type {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column type.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column type.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column type.picture
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private String picture;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column type.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Date startTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column type.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Date editTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column type.is_show
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private Boolean isShow;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column type.id
	 * @return  the value of type.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column type.id
	 * @param id  the value for type.id
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column type.name
	 * @return  the value of type.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column type.name
	 * @param name  the value for type.name
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column type.picture
	 * @return  the value of type.picture
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column type.picture
	 * @param picture  the value for type.picture
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column type.start_time
	 * @return  the value of type.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column type.start_time
	 * @param startTime  the value for type.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column type.edit_time
	 * @return  the value of type.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Date getEditTime() {
		return editTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column type.edit_time
	 * @param editTime  the value for type.edit_time
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column type.is_show
	 * @return  the value of type.is_show
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Boolean getIsShow() {
		return isShow;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column type.is_show
	 * @param isShow  the value for type.is_show
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void setIsShow(Boolean isShow) {
		this.isShow = isShow;
	}
}