package cn.guddqs.peakshop.entity;

import java.util.Date;

public class UserInfo {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user_info.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user_info.openid
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private String openid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user_info.jifen
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Float jifen;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user_info.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Date startTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user_info.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Date endTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user_info.nick_name
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private String nickName;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user_info.id
	 * @return  the value of user_info.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user_info.id
	 * @param id  the value for user_info.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user_info.openid
	 * @return  the value of user_info.openid
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user_info.openid
	 * @param openid  the value for user_info.openid
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user_info.jifen
	 * @return  the value of user_info.jifen
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Float getJifen() {
		return jifen;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user_info.jifen
	 * @param jifen  the value for user_info.jifen
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setJifen(Float jifen) {
		this.jifen = jifen;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user_info.start_time
	 * @return  the value of user_info.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user_info.start_time
	 * @param startTime  the value for user_info.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user_info.end_time
	 * @return  the value of user_info.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user_info.end_time
	 * @param endTime  the value for user_info.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user_info.nick_name
	 * @return  the value of user_info.nick_name
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user_info.nick_name
	 * @param nickName  the value for user_info.nick_name
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
}