package cn.guddqs.peakshop.entity;

public class Video {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column video.id
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column video.path
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    private String path;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column video.path
     *
     * @return the value of video.path
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column video.path
     *
     * @param path the value for video.path
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public void setPath(String path) {
        this.path = path;
    }
}