package cn.guddqs.peakshop.entity;

import java.util.Date;

public class Wuliu {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wuliu.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wuliu.wuliu_number
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private String wuliuNumber;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wuliu.descprit
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private String descprit;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wuliu.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Date startTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column wuliu.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private Date endTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wuliu.id
	 * @return  the value of wuliu.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wuliu.id
	 * @param id  the value for wuliu.id
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wuliu.wuliu_number
	 * @return  the value of wuliu.wuliu_number
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public String getWuliuNumber() {
		return wuliuNumber;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wuliu.wuliu_number
	 * @param wuliuNumber  the value for wuliu.wuliu_number
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setWuliuNumber(String wuliuNumber) {
		this.wuliuNumber = wuliuNumber;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wuliu.descprit
	 * @return  the value of wuliu.descprit
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public String getDescprit() {
		return descprit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wuliu.descprit
	 * @param descprit  the value for wuliu.descprit
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setDescprit(String descprit) {
		this.descprit = descprit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wuliu.start_time
	 * @return  the value of wuliu.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wuliu.start_time
	 * @param startTime  the value for wuliu.start_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column wuliu.end_time
	 * @return  the value of wuliu.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column wuliu.end_time
	 * @param endTime  the value for wuliu.end_time
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}
}