package cn.guddqs.peakshop.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import cn.guddqs.peakshop.entity.AddressInfo;
import cn.guddqs.peakshop.entity.AddressInfoExample;

public class AddressInfoDAOImpl extends SqlMapClientDaoSupport implements AddressInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public AddressInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void insert(AddressInfo record) {
		getSqlMapClientTemplate().insert("address_info.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByPrimaryKey(AddressInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"address_info.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByPrimaryKeySelective(AddressInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"address_info.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public List selectByExample(AddressInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"address_info.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public AddressInfo selectByPrimaryKey(Integer id) {
		AddressInfo key = new AddressInfo();
		key.setId(id);
		AddressInfo record = (AddressInfo) getSqlMapClientTemplate()
				.queryForObject(
						"address_info.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int deleteByExample(AddressInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"address_info.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		AddressInfo key = new AddressInfo();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"address_info.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int countByExample(AddressInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"address_info.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByExampleSelective(AddressInfo record,
			AddressInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"address_info.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByExample(AddressInfo record, AddressInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"address_info.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private static class UpdateByExampleParms extends AddressInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, AddressInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}