package cn.guddqs.peakshop.dao;

import java.util.List;

import cn.guddqs.peakshop.entity.AddressInfo;
import cn.guddqs.peakshop.entity.AddressInfoExample;

public interface AddressInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	void insert(AddressInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByPrimaryKey(AddressInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByPrimaryKeySelective(AddressInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	List selectByExample(AddressInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	AddressInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int deleteByExample(AddressInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int countByExample(AddressInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByExampleSelective(AddressInfo record, AddressInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table address_info
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByExample(AddressInfo record, AddressInfoExample example);
}