package cn.guddqs.peakshop.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import cn.guddqs.peakshop.entity.Cart;
import cn.guddqs.peakshop.entity.CartExample;

public class CartDAOImpl extends SqlMapClientDaoSupport implements CartDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public CartDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void insert(Cart record) {
		getSqlMapClientTemplate().insert("cart.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByPrimaryKey(Cart record) {
		int rows = getSqlMapClientTemplate().update(
				"cart.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByPrimaryKeySelective(Cart record) {
		int rows = getSqlMapClientTemplate().update(
				"cart.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public List selectByExample(CartExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"cart.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Cart selectByPrimaryKey(Integer id) {
		Cart key = new Cart();
		key.setId(id);
		Cart record = (Cart) getSqlMapClientTemplate().queryForObject(
				"cart.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int deleteByExample(CartExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"cart.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		Cart key = new Cart();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"cart.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int countByExample(CartExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"cart.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByExampleSelective(Cart record, CartExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"cart.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByExample(Cart record, CartExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"cart.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private static class UpdateByExampleParms extends CartExample {
		private Object record;

		public UpdateByExampleParms(Object record, CartExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}