package cn.guddqs.peakshop.dao;

import java.util.List;

import cn.guddqs.peakshop.entity.Cart;
import cn.guddqs.peakshop.entity.CartExample;

public interface CartDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	void insert(Cart record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByPrimaryKey(Cart record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByPrimaryKeySelective(Cart record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	List selectByExample(CartExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	Cart selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int deleteByExample(CartExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int countByExample(CartExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByExampleSelective(Cart record, CartExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table cart
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByExample(Cart record, CartExample example);
}