package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.Color;
import cn.guddqs.peakshop.entity.ColorExample;
import java.util.List;

public interface ColorDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	void insert(Color record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKey(Color record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKeySelective(Color record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	List selectByExample(ColorExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	Color selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByExample(ColorExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int countByExample(ColorExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExampleSelective(Color record, ColorExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExample(Color record, ColorExample example);
}