package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.MerchantInfo;
import cn.guddqs.peakshop.entity.MerchantInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MerchantInfoDAOImpl extends SqlMapClientDaoSupport implements MerchantInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public MerchantInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public void insert(MerchantInfo record) {
		getSqlMapClientTemplate().insert(
				"merchant_info.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public int updateByPrimaryKey(MerchantInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"merchant_info.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public int updateByPrimaryKeySelective(MerchantInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"merchant_info.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public List selectByExample(MerchantInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"merchant_info.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public MerchantInfo selectByPrimaryKey(Integer id) {
		MerchantInfo key = new MerchantInfo();
		key.setId(id);
		MerchantInfo record = (MerchantInfo) getSqlMapClientTemplate()
				.queryForObject(
						"merchant_info.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public int deleteByExample(MerchantInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"merchant_info.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public int deleteByPrimaryKey(Integer id) {
		MerchantInfo key = new MerchantInfo();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"merchant_info.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public int countByExample(MerchantInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"merchant_info.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public int updateByExampleSelective(MerchantInfo record,
			MerchantInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("merchant_info.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	public int updateByExample(MerchantInfo record, MerchantInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"merchant_info.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	private static class UpdateByExampleParms extends MerchantInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, MerchantInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}