package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.MerchantInfo;
import cn.guddqs.peakshop.entity.MerchantInfoExample;
import java.util.List;

public interface MerchantInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	void insert(MerchantInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	int updateByPrimaryKey(MerchantInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	int updateByPrimaryKeySelective(MerchantInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	List selectByExample(MerchantInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	MerchantInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	int deleteByExample(MerchantInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	int countByExample(MerchantInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	int updateByExampleSelective(MerchantInfo record,
			MerchantInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table merchant_info
	 * @abatorgenerated  Fri Oct 13 16:11:39 CST 2017
	 */
	int updateByExample(MerchantInfo record, MerchantInfoExample example);
}