package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.ProductColor;
import cn.guddqs.peakshop.entity.ProductColorExample;
import java.util.List;

public interface ProductColorDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	void insert(ProductColor record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKey(ProductColor record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKeySelective(ProductColor record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	List selectByExample(ProductColorExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	ProductColor selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByExample(ProductColorExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int countByExample(ProductColorExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExampleSelective(ProductColor record,
			ProductColorExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExample(ProductColor record, ProductColorExample example);
}