package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.Product;
import cn.guddqs.peakshop.entity.ProductExample;
import java.util.List;

public interface ProductDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	void insert(Product record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByPrimaryKey(Product record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByPrimaryKeySelective(Product record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	List selectByExample(ProductExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	Product selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int deleteByExample(ProductExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int countByExample(ProductExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByExampleSelective(Product record, ProductExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByExample(Product record, ProductExample example);
}