package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.ProductDetail;
import cn.guddqs.peakshop.entity.ProductDetailExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProductDetailDAOImpl extends SqlMapClientDaoSupport implements ProductDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public ProductDetailDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void insert(ProductDetail record) {
		getSqlMapClientTemplate().insert(
				"product_detail.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKey(ProductDetail record) {
		int rows = getSqlMapClientTemplate().update(
				"product_detail.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKeySelective(ProductDetail record) {
		int rows = getSqlMapClientTemplate().update(
				"product_detail.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public List selectByExample(ProductDetailExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"product_detail.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public ProductDetail selectByPrimaryKey(Integer id) {
		ProductDetail key = new ProductDetail();
		key.setId(id);
		ProductDetail record = (ProductDetail) getSqlMapClientTemplate()
				.queryForObject(
						"product_detail.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByExample(ProductDetailExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"product_detail.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		ProductDetail key = new ProductDetail();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"product_detail.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int countByExample(ProductDetailExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"product_detail.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExampleSelective(ProductDetail record,
			ProductDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"product_detail.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExample(ProductDetail record,
			ProductDetailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"product_detail.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private static class UpdateByExampleParms extends ProductDetailExample {
		private Object record;

		public UpdateByExampleParms(Object record, ProductDetailExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}