package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.ProductSize;
import cn.guddqs.peakshop.entity.ProductSizeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProductSizeDAOImpl extends SqlMapClientDaoSupport implements ProductSizeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public ProductSizeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public void insert(ProductSize record) {
		getSqlMapClientTemplate().insert("product_size.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public int updateByPrimaryKey(ProductSize record) {
		int rows = getSqlMapClientTemplate().update(
				"product_size.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public int updateByPrimaryKeySelective(ProductSize record) {
		int rows = getSqlMapClientTemplate().update(
				"product_size.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public List selectByExample(ProductSizeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"product_size.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public ProductSize selectByPrimaryKey(Integer id) {
		ProductSize key = new ProductSize();
		key.setId(id);
		ProductSize record = (ProductSize) getSqlMapClientTemplate()
				.queryForObject(
						"product_size.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public int deleteByExample(ProductSizeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"product_size.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		ProductSize key = new ProductSize();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"product_size.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public int countByExample(ProductSizeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"product_size.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public int updateByExampleSelective(ProductSize record,
			ProductSizeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"product_size.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	public int updateByExample(ProductSize record, ProductSizeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"product_size.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	private static class UpdateByExampleParms extends ProductSizeExample {
		private Object record;

		public UpdateByExampleParms(Object record, ProductSizeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}