package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.ProductSize;
import cn.guddqs.peakshop.entity.ProductSizeExample;
import java.util.List;

public interface ProductSizeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	void insert(ProductSize record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	int updateByPrimaryKey(ProductSize record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	int updateByPrimaryKeySelective(ProductSize record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	List selectByExample(ProductSizeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	ProductSize selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	int deleteByExample(ProductSizeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	int countByExample(ProductSizeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	int updateByExampleSelective(ProductSize record, ProductSizeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_size
	 * @abatorgenerated  Fri Jan 25 20:43:11 CST 2019
	 */
	int updateByExample(ProductSize record, ProductSizeExample example);
}