package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.ProductColor;
import cn.guddqs.peakshop.entity.ProductColorExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProductColorDAOImpl extends SqlMapClientDaoSupport implements ProductColorDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public ProductColorDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void insert(ProductColor record) {
		getSqlMapClientTemplate().insert(
				"product_color.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKey(ProductColor record) {
		int rows = getSqlMapClientTemplate().update(
				"product_color.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKeySelective(ProductColor record) {
		int rows = getSqlMapClientTemplate().update(
				"product_color.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public List selectByExample(ProductColorExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"product_color.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public ProductColor selectByPrimaryKey(Integer id) {
		ProductColor key = new ProductColor();
		key.setId(id);
		ProductColor record = (ProductColor) getSqlMapClientTemplate()
				.queryForObject(
						"product_color.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByExample(ProductColorExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"product_color.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		ProductColor key = new ProductColor();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"product_color.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int countByExample(ProductColorExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"product_color.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExampleSelective(ProductColor record,
			ProductColorExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("product_color.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExample(ProductColor record, ProductColorExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"product_color.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table product_color
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private static class UpdateByExampleParms extends ProductColorExample {
		private Object record;

		public UpdateByExampleParms(Object record, ProductColorExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}