package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.Product;
import cn.guddqs.peakshop.entity.ProductExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProductDAOImpl extends SqlMapClientDaoSupport implements ProductDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public ProductDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void insert(Product record) {
		getSqlMapClientTemplate().insert("product.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByPrimaryKey(Product record) {
		int rows = getSqlMapClientTemplate().update(
				"product.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByPrimaryKeySelective(Product record) {
		int rows = getSqlMapClientTemplate().update(
				"product.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public List selectByExample(ProductExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"product.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Product selectByPrimaryKey(Integer id) {
		Product key = new Product();
		key.setId(id);
		Product record = (Product) getSqlMapClientTemplate().queryForObject(
				"product.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int deleteByExample(ProductExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"product.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		Product key = new Product();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"product.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int countByExample(ProductExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"product.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByExampleSelective(Product record, ProductExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"product.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByExample(Product record, ProductExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"product.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table product
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private static class UpdateByExampleParms extends ProductExample {
		private Object record;

		public UpdateByExampleParms(Object record, ProductExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}