package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.ProductDetail;
import cn.guddqs.peakshop.entity.ProductDetailExample;
import java.util.List;

public interface ProductDetailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	void insert(ProductDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKey(ProductDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKeySelective(ProductDetail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	List selectByExample(ProductDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	ProductDetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByExample(ProductDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int countByExample(ProductDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExampleSelective(ProductDetail record,
			ProductDetailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product_detail
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExample(ProductDetail record, ProductDetailExample example);
}