package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.Size;
import cn.guddqs.peakshop.entity.SizeExample;
import java.util.List;

public interface SizeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	void insert(Size record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKey(Size record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKeySelective(Size record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	List selectByExample(SizeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	Size selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByExample(SizeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int countByExample(SizeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExampleSelective(Size record, SizeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExample(Size record, SizeExample example);
}