package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.Size;
import cn.guddqs.peakshop.entity.SizeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SizeDAOImpl extends SqlMapClientDaoSupport implements SizeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public SizeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void insert(Size record) {
		getSqlMapClientTemplate().insert("size.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKey(Size record) {
		int rows = getSqlMapClientTemplate().update(
				"size.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKeySelective(Size record) {
		int rows = getSqlMapClientTemplate().update(
				"size.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public List selectByExample(SizeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"size.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Size selectByPrimaryKey(Integer id) {
		Size key = new Size();
		key.setId(id);
		Size record = (Size) getSqlMapClientTemplate().queryForObject(
				"size.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByExample(SizeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"size.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		Size key = new Size();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"size.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int countByExample(SizeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"size.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExampleSelective(Size record, SizeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"size.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExample(Size record, SizeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"size.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table size
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private static class UpdateByExampleParms extends SizeExample {
		private Object record;

		public UpdateByExampleParms(Object record, SizeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}