package cn.guddqs.peakshop.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import cn.guddqs.peakshop.entity.Store;
import cn.guddqs.peakshop.entity.StoreExample;

public class StoreDAOImpl extends SqlMapClientDaoSupport implements StoreDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public StoreDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void insert(Store record) {
		getSqlMapClientTemplate()
				.insert("store.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKey(Store record) {
		int rows = getSqlMapClientTemplate().update(
				"store.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKeySelective(Store record) {
		int rows = getSqlMapClientTemplate().update(
				"store.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public List selectByExample(StoreExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"store.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Store selectByPrimaryKey(Integer id) {
		Store key = new Store();
		key.setId(id);
		Store record = (Store) getSqlMapClientTemplate().queryForObject(
				"store.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByExample(StoreExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"store.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		Store key = new Store();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"store.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int countByExample(StoreExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"store.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExampleSelective(Store record, StoreExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"store.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExample(Store record, StoreExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"store.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private static class UpdateByExampleParms extends StoreExample {
		private Object record;

		public UpdateByExampleParms(Object record, StoreExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}