package cn.guddqs.peakshop.dao;

import java.util.List;

import cn.guddqs.peakshop.entity.Store;
import cn.guddqs.peakshop.entity.StoreExample;

public interface StoreDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	void insert(Store record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKey(Store record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKeySelective(Store record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	List selectByExample(StoreExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	Store selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByExample(StoreExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int countByExample(StoreExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExampleSelective(Store record, StoreExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table store
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExample(Store record, StoreExample example);
}