package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.TradeOrder;
import cn.guddqs.peakshop.entity.TradeOrderExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TradeOrderDAOImpl extends SqlMapClientDaoSupport implements TradeOrderDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public TradeOrderDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void insert(TradeOrder record) {
		getSqlMapClientTemplate().insert("trade_order.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByPrimaryKey(TradeOrder record) {
		int rows = getSqlMapClientTemplate().update(
				"trade_order.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByPrimaryKeySelective(TradeOrder record) {
		int rows = getSqlMapClientTemplate().update(
				"trade_order.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public List selectByExample(TradeOrderExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"trade_order.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public TradeOrder selectByPrimaryKey(Integer id) {
		TradeOrder key = new TradeOrder();
		key.setId(id);
		TradeOrder record = (TradeOrder) getSqlMapClientTemplate()
				.queryForObject(
						"trade_order.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int deleteByExample(TradeOrderExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"trade_order.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		TradeOrder key = new TradeOrder();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"trade_order.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int countByExample(TradeOrderExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"trade_order.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByExampleSelective(TradeOrder record,
			TradeOrderExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"trade_order.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByExample(TradeOrder record, TradeOrderExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"trade_order.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table trade_order
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private static class UpdateByExampleParms extends TradeOrderExample {
		private Object record;

		public UpdateByExampleParms(Object record, TradeOrderExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}