package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.Type;
import cn.guddqs.peakshop.entity.TypeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TypeDAOImpl extends SqlMapClientDaoSupport implements TypeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public TypeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public void insert(Type record) {
		getSqlMapClientTemplate().insert("type.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByPrimaryKey(Type record) {
		int rows = getSqlMapClientTemplate().update(
				"type.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByPrimaryKeySelective(Type record) {
		int rows = getSqlMapClientTemplate().update(
				"type.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public List selectByExample(TypeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"type.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public Type selectByPrimaryKey(Integer id) {
		Type key = new Type();
		key.setId(id);
		Type record = (Type) getSqlMapClientTemplate().queryForObject(
				"type.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int deleteByExample(TypeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"type.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		Type key = new Type();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"type.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int countByExample(TypeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"type.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByExampleSelective(Type record, TypeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"type.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	public int updateByExample(Type record, TypeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"type.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	private static class UpdateByExampleParms extends TypeExample {
		private Object record;

		public UpdateByExampleParms(Object record, TypeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}