package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.Type;
import cn.guddqs.peakshop.entity.TypeExample;
import java.util.List;

public interface TypeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	void insert(Type record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByPrimaryKey(Type record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByPrimaryKeySelective(Type record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	List selectByExample(TypeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	Type selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int deleteByExample(TypeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int countByExample(TypeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByExampleSelective(Type record, TypeExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table type
	 * @abatorgenerated  Fri Jan 25 20:43:09 CST 2019
	 */
	int updateByExample(Type record, TypeExample example);
}