package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.UserInfo;
import cn.guddqs.peakshop.entity.UserInfoExample;
import java.util.List;

public interface UserInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	void insert(UserInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKey(UserInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByPrimaryKeySelective(UserInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	List selectByExample(UserInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	UserInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByExample(UserInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int countByExample(UserInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExampleSelective(UserInfo record, UserInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	int updateByExample(UserInfo record, UserInfoExample example);
}