package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.UserInfo;
import cn.guddqs.peakshop.entity.UserInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserInfoDAOImpl extends SqlMapClientDaoSupport implements UserInfoDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public UserInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void insert(UserInfo record) {
		getSqlMapClientTemplate().insert("user_info.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKey(UserInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"user_info.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKeySelective(UserInfo record) {
		int rows = getSqlMapClientTemplate()
				.update("user_info.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public List selectByExample(UserInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"user_info.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public UserInfo selectByPrimaryKey(Integer id) {
		UserInfo key = new UserInfo();
		key.setId(id);
		UserInfo record = (UserInfo) getSqlMapClientTemplate().queryForObject(
				"user_info.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByExample(UserInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"user_info.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		UserInfo key = new UserInfo();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"user_info.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int countByExample(UserInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"user_info.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExampleSelective(UserInfo record, UserInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"user_info.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExample(UserInfo record, UserInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"user_info.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table user_info
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private static class UpdateByExampleParms extends UserInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}