package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.Video;
import cn.guddqs.peakshop.entity.VideoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VideoDAOImpl extends SqlMapClientDaoSupport implements VideoDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public VideoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public void insert(Video record) {
        getSqlMapClientTemplate().insert("video.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public int updateByPrimaryKey(Video record) {
        int rows = getSqlMapClientTemplate().update("video.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public int updateByPrimaryKeySelective(Video record) {
        int rows = getSqlMapClientTemplate().update("video.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public List selectByExample(VideoExample example) {
        List list = getSqlMapClientTemplate().queryForList("video.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public Video selectByPrimaryKey(Integer id) {
        Video key = new Video();
        key.setId(id);
        Video record = (Video) getSqlMapClientTemplate().queryForObject("video.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public int deleteByExample(VideoExample example) {
        int rows = getSqlMapClientTemplate().delete("video.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        Video key = new Video();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("video.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public int countByExample(VideoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("video.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public int updateByExampleSelective(Video record, VideoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("video.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    public int updateByExample(Video record, VideoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("video.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    private static class UpdateByExampleParms extends VideoExample {
        private Object record;

        public UpdateByExampleParms(Object record, VideoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}