package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.Video;
import cn.guddqs.peakshop.entity.VideoExample;
import java.util.List;

public interface VideoDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    void insert(Video record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    int updateByPrimaryKey(Video record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    int updateByPrimaryKeySelective(Video record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    List selectByExample(VideoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    Video selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    int deleteByExample(VideoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    int countByExample(VideoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    int updateByExampleSelective(Video record, VideoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table video
     *
     * @abatorgenerated Wed Oct 11 17:35:11 CST 2017
     */
    int updateByExample(Video record, VideoExample example);
}