package cn.guddqs.peakshop.dao;

import cn.guddqs.peakshop.entity.Wuliu;
import cn.guddqs.peakshop.entity.WuliuExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WuliuDAOImpl extends SqlMapClientDaoSupport implements WuliuDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public WuliuDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public void insert(Wuliu record) {
		getSqlMapClientTemplate()
				.insert("wuliu.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKey(Wuliu record) {
		int rows = getSqlMapClientTemplate().update(
				"wuliu.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByPrimaryKeySelective(Wuliu record) {
		int rows = getSqlMapClientTemplate().update(
				"wuliu.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public List selectByExample(WuliuExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"wuliu.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public Wuliu selectByPrimaryKey(Integer id) {
		Wuliu key = new Wuliu();
		key.setId(id);
		Wuliu record = (Wuliu) getSqlMapClientTemplate().queryForObject(
				"wuliu.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByExample(WuliuExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"wuliu.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int deleteByPrimaryKey(Integer id) {
		Wuliu key = new Wuliu();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"wuliu.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int countByExample(WuliuExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"wuliu.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExampleSelective(Wuliu record, WuliuExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"wuliu.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	public int updateByExample(Wuliu record, WuliuExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"wuliu.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table wuliu
	 * @abatorgenerated  Fri Jan 25 20:43:10 CST 2019
	 */
	private static class UpdateByExampleParms extends WuliuExample {
		private Object record;

		public UpdateByExampleParms(Object record, WuliuExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}